":packadd! ack
":packadd! ale
":packadd! base16-vim
":packadd! coc
":packadd! ctrlp.vim
":packadd! dart-vim-plugin
":packadd! editorconfig-vim
":packadd! fugitive
":packadd! fzf
":packadd! gist-vim
":packadd! gitcopilot
":packadd! grunt.vim
":packadd! javascript-libraries-syntax.vim
":packadd! keyfile
":packadd! minibufexpl.vim
":packadd! nerdtree
":packadd! omnisharp-vim
":packadd! php-cs-fixer
":packadd! sharpenup
":packadd! syntastic
":packadd! tabular
":packadd! ultisnips
":packadd! undotree
":packadd! vim-abolish
":packadd! vim-ag
":packadd! vim-airline
":packadd! vim-airline-themes
":packadd! vim-blazek
":packadd! vim-buffer-explorer-plugin
":packadd! vim-characterize
":packadd! vim-coffee-script
":packadd! vim-elixir
":packadd! vim-fugitive
":packadd! vim-gitgutter
":packadd! vim-haml
":packadd! vim-javascript-syntax
":packadd! vim-json
":packadd! vim-jsx-pretty
":packadd! vim-markdown
":packadd! vim-pastie
":packadd! vim-pathogen
":packadd! vim-prettier
":packadd! vim-repeat
":packadd! vim-snippets
":packadd! vim-surround
":packadd! vim-tcomment
":packadd! vim-webapi
":packadd! vim-webdevicons
":packadd! yats
":packadd! ycm
